[package]
name = "smart_term"
version = "1.0.0"
edition = "2021"
description = "Context-aware intelligent terminal with OS isolation"
license = "MIT"
authors = ["Arsalan Shoaei Ahmad Abad"]

[dependencies]
crossterm = "0.27"
rusqlite = { version = "0.30", features = ["bundled"] }
dirs = "5.0"
portable-pty = "0.8"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"

[package.metadata.generate-rpm]
assets = [
    { source = "target/release/smart_term", dest = "/usr/local/bin/smart", mode = "755" }
]